### ISSUE TITLE
add general sports analytics packages

### ISSUE THREAD

**Issue by beanumber** [beanumber/ctv-sportsanalytics#10]
* `aRbs`
* `mvglmmRank`
* `SportsAnalytics`
* `TouRnament`
* `piratings`

_Originally posted by @beanumber in https://github.com/beanumber/ctv-sportsanalytics/issues/3#issuecomment-933576314_

**Comment by beanumber** [comment]
* `sportyR`

**Comment by gjm112** [comment]
Sporty R added.
