### ISSUE TITLE
what about a section on non-CRAN packages? 

### ISSUE THREAD

**Issue by beanumber** [beanumber/ctv-sportsanalytics#14]
A note?

**Comment by math-mcshane** [comment]
I would add `rStrava` which I thought was on CRAN but apparently is not: https://github.com/fawda123/rStrava

**Comment by beanumber** [comment]
I'm going to close this issue because:

- We've done public outreach already
- We have a lot of packages listed already
- @fawda123 's experience is informative: there are too many non-CRAN packages in various states of functionality. Maybe the desire to appear on this CTV provides the motivation that people need to bring their packages into CRAN-compliance, which is probably good for everyone.
