### ISSUE TITLE
College Football Package `cfbfastR`

### ISSUE THREAD

**Issue by math-mcshane** [beanumber/ctv-sportsanalytics#21]
I noticed there was a lack of college football packages listed here and re-discovered this package by @saiemgilani that would be good to add to the CRAN view @qntkhvn 
https://saiemgilani.github.io/cfbfastR/index.html 

And anything else by him that's on CRAN (I'll leave Saiem to note whether there's something else missing), as well as this non-CRAN view issue: https://github.com/beanumber/ctv-sportsanalytics/issues/14 

-[Ryan](https://twitter.com/math_mcshane)

**Comment by saiemgilani** [comment]
`hoopR` will be resubmitted with corrections and should be on CRAN next week. `wehoop` is on CRAN now. I will submit `recruitR` and `powerplay` in the coming weeks.

**Comment by qntkhvn** [comment]
Got it; thanks @math-mcshane and @saiemgilani!

**Comment by saiemgilani** [comment]
[**`hoopR`**](https://saiemgilani.github.io/hoopR/) is now on CRAN: https://cran.r-project.org/package=hoopR

**Comment by saiemgilani** [comment]
[**fastRhockey**](https://benhowell71.github.io/fastRhockey/) is now on CRAN:  https://cran.r-project.org/package=fastRhockey 
This is both an NHL Stats API and Premier Hockey Federation API wrapper with loader and database functions in similar fashion to other packages I have created. ```powerplay``` will now be archived and not submitted to CRAN. 

recruitR is still in development and may be a while before submission. baseballr may be submitted at some point in the near future, it is nominally ready but I would like to fine-tune a few things before we submit.

**Comment by saiemgilani** [comment]
Also, @JaseZiv's [**`worldfootballR`**](https://jaseziv.github.io/worldfootballR/) package is now on CRAN: https://cran.r-project.org/package=worldfootballR

A wrapper for extracting world football (soccer) data from FBref, Transfermark, Understat and fotmob

**Comment by beanumber** [comment]
Thanks @saiemgilani
