### ISSUE TITLE
`squashinformr` for the list

### ISSUE THREAD

**Issue by math-mcshane** [beanumber/ctv-sportsanalytics#24]
Squash data acquisition package on CRAN
https://cran.r-project.org/web/packages/squashinformr/index.html

**Comment by beanumber** [comment]
Thanks! We will add this to the next iteration.

**Comment by qntkhvn** [comment]
Squash!!!

Although... I checked today and `squashinformr` is no longer on CRAN. Hopefully it's just a minor bug fix.

**Comment by qntkhvn** [comment]
Good news... `squashinformr` is back on CRAN. I've added it to the list.
(@beanumber I couldn't find the squash emoji, is there even one...?)

**Comment by math-mcshane** [comment]
Close enough: 🎾

**Comment by beanumber** [comment]
Wait, how do we not have any tennis packages?

**Comment by qntkhvn** [comment]
There’s not a single tennis pkg on CRAN. I guess we could have a section on “Racket sports 🎾🏓🏸” which includes squash.

**Comment by beanumber** [comment]
I love that idea!

**Comment by qntkhvn** [comment]
Changes have been implemented.
