### ISSUE TITLE
think about core packages

### ISSUE THREAD

**Issue by beanumber** [beanumber/ctv-sportsanalytics#28]
> For the "core" packages I suggest to simply go with some of the most substantial packages for some of the more prominent sports.

- `Lahman`
- `teamcolors`
- `nflfastR`

Investigate most popular packages and consider putting them in the core.

**Comment by qntkhvn** [comment]
I just took a quick look at this. ([R script](https://github.com/beanumber/ctv-sportsanalytics/blob/master/R/cran_downloads.R))

The top 10 in terms of cumulative downloads are 

* `Lahman`
* `BradleyTerry2`
* `pitchRx`
* `SportsAnalytics`
* `cricketr`
* `fbRanks`
* `trackeR`
* `BAwiR`
* `mvglmmRank`
* `odds.converter`

(`teamcolors`' rank is 20.)

**Comment by qntkhvn** [comment]
Sure. I have specified `priority = "core"` for those packages. I did not include `SportsAnalytics` since the package looks incomplete and it was last updated in 2013. I also included `nflfastR`, given its recent popularity.

**Comment by tanho63** [comment]
commenting on `nflfastR` as a maintainer I think most people should use `nflreadr`, which provides access to the "finished product" of nflfastR modelling

**Comment by qntkhvn** [comment]
I added `nflverse`, which consists of both `nflfastR` and `nflreadr`, as a core pkg. See #31.

**Comment by qntkhvn** [comment]
Sure. I've added `baseballr` to the core list.
