### ISSUE TITLE
add soccer packages

### ISSUE THREAD

**Issue by beanumber** [beanumber/ctv-sportsanalytics#4]
* `qqr`
* `ggsoccer`
* `socceR`
* `engsoccerdata`
* `fbRanks`
* `mlsjunkgen`

**Comment by beanumber** [comment]
* `stockfish`

**Comment by beanumber** [comment]
* `cricketr`

**Comment by qntkhvn** [comment]
`mlsjunkgen`, though containing "mls", is not related to Major League Soccer.
